<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-windows;net11.0-windows</TargetFrameworks>
		<LangVersion>15</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Used for CI/CD on Ubuntu -->
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<UseWindowsForms>true</UseWindowsForms>
		<Version>$(KarnaughMapVersion)</Version>
		<Description>This package contains a .NET Core Windows Forms control that renders a Karnaugh-map which is fully interactive.</Description>
		<Authors>Pieterjan De Clippel</Authors>
		<Company>MintPlayer</Company>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/MintPlayer/MintPlayer.DotnetDesktop.Tools/KarnaughMap/MintPlayer.KarnaughMap</PackageProjectUrl>
		<RepositoryUrl>https://github.com/MintPlayer/MintPlayer.DotnetDesktop.Tools</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>Karnaugh-map, Quine McCluskey</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WinForms.Designer.SDK" Version="1.6.0" />
		<PackageReference Include="MintPlayer.ObservableCollection" Version="11.0.0-rc.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\QuineMcCluskey\MintPlayer.QuineMcCluskey.Abstractions\MintPlayer.QuineMcCluskey.Abstractions.csproj" />
	  <ProjectReference Include="..\MintPlayer.KarnaughMap.Abstractions\MintPlayer.KarnaughMap.Abstractions.csproj" />
	</ItemGroup>

</Project>
