<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>MintPlayer.Bacon.Editor</AssemblyName>
		<RootNamespace>MintPlayer.Bacon.Editor</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Bacon.Core\Bacon.Core.csproj" />
	</ItemGroup>
</Project>
