<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0-windows</TargetFramework>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MintPlayer.IconUtils\MintPlayer.IconUtils.csproj" />
	</ItemGroup>

</Project>
