<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Icon is only available on Windows -->
		<!-- https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#reason-for-change -->
		<TargetFrameworks>net10.0-windows;net11.0-windows</TargetFrameworks>
		<!-- Used for CI/CD on Ubuntu -->
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>MintPlayer.IconUtils</PackageId>
		<Authors>Pieterjan De Clippel</Authors>
		<Company>MintPlayer</Company>
		<Description>Extract Icons</Description>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/MintPlayer/MintPlayer.DotnetDesktop.Tools/IconUtils/MintPlayer.IconUtils</PackageProjectUrl>
		<RepositoryUrl>https://github.com/MintPlayer/MintPlayer.DotnetDesktop.Tools</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>Icon, Split, Extract</PackageTags>
		<Version>$(IconUtilsVersion)</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>TRACE;NETCORE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MintPlayer.IconUtils.Abstractions\MintPlayer.IconUtils.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="11.0.0-rc.1.26425.128" />
	</ItemGroup>

</Project>
